"""added-role

Revision ID: 9eee13d285e9
Revises: 
Create Date: 2025-03-29 06:07:06.813542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eee13d285e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('table_booking',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('booking_id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('booking_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['table_booking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    op.drop_table('table_booking')
    op.drop_table('user')
    # ### end Alembic commands ###
