"""changesd-models-of-tabel

Revision ID: dafa4400093e
Revises: 
Create Date: 2025-03-30 22:15:28.807728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafa4400093e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('table_booking',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('order_id', sa.BINARY(length=16), nullable=False),
    sa.Column('food_id', sa.BINARY(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('booking_id', sa.BINARY(length=16), nullable=True),
    sa.Column('user_id', sa.BINARY(length=16), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('booking_time', sa.Time(), nullable=True),
    sa.Column('booking_status', sa.Enum('AVAILABLE', 'PENDING', 'CONFIRMED', name='bookingstatus'), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['table_booking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    op.drop_table('order_item')
    op.drop_table('table_booking')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('food_item')
    # ### end Alembic commands ###
