"""added-recipt

Revision ID: f9945311aff5
Revises: dafa4400093e
Create Date: 2025-03-31 02:02:16.545738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9945311aff5'
down_revision = 'dafa4400093e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('order_id', sa.BINARY(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt')
    # ### end Alembic commands ###
